"""Singlish Word Bank — examples generated live by Claude at post time.
nsfw=True entries are filtered out if ALLOW_NSFW env var is not set.
"""

SINGLISH_WORDS = [
    {"word":"lah","type":"particle","pronunciation":"lah","meaning":"The most iconic Singlish particle. Softens commands, adds emphasis, or expresses exasperation depending on tone."},
    {"word":"leh","type":"particle","pronunciation":"leh","meaning":"Expresses mild complaint, seeks agreement, or gently softens a statement. Slightly more pleading than 'lah'."},
    {"word":"lor","type":"particle","pronunciation":"lor","meaning":"Expresses resignation or states the obvious. 'That's just how it is, nothing can be done.'"},
    {"word":"meh","type":"particle","pronunciation":"meh","meaning":"A tag question expressing surprise or doubt, implying the speaker expected something different."},
    {"word":"sia","type":"particle","pronunciation":"see-ah","meaning":"Sentence-ending particle expressing admiration, surprise, or strong emphasis. Like 'wow' or 'man'."},
    {"word":"wor","type":"particle","pronunciation":"wor","meaning":"Indicates new or mildly surprising information being shared. Softens a statement with a sense of discovery."},
    {"word":"hor","type":"particle","pronunciation":"hor","meaning":"Tag particle seeking agreement or confirmation from the listener. Like 'right?' or 'isn't it?'"},
    {"word":"ah","type":"particle","pronunciation":"ah","meaning":"Versatile particle that softens statements, seeks mild confirmation, or adds a cautioning tone."},
    {"word":"liao","type":"particle / adverb","pronunciation":"lee-ow","meaning":"Already. From Hokkien \u2014 indicates a completed action or changed state. More final than standard 'already'."},
    {"word":"one","type":"particle","pronunciation":"one","meaning":"Sentence-ending emphatic particle asserting a fact, often with conviction or slight defensiveness."},
    {"word":"nia","type":"particle","pronunciation":"knee-ah","meaning":"Only, merely, just. From Hokkien \u2014 minimises or downplays the extent of something."},
    {"word":"mah","type":"particle","pronunciation":"mah","meaning":"Expresses that something is obvious or self-evident. 'Of course' or 'obviously lah'."},
    {"word":"bah","type":"particle","pronunciation":"bah","meaning":"Expresses reluctant agreement, resignation, or mild uncertainty. 'I suppose so' or 'fine then'."},
    {"word":"isit","type":"particle / question","pronunciation":"iz-zit","meaning":"Is it? A tag question or response particle expressing surprise, mild disbelief, or seeking confirmation."},
    {"word":"orh","type":"particle","pronunciation":"or","meaning":"Acknowledges that you've understood something. Like 'I see', 'okay', or 'noted'."},
    {"word":"yalah","type":"exclamation / particle","pronunciation":"yah-lah","meaning":"Exasperated or emphatic agreement. Combines 'ya' and 'lah' \u2014 'yes yes, I know already lah'."},
    {"word":"yah","type":"particle / exclamation","pronunciation":"yah","meaning":"Yes, or an affirmative acknowledgement. Used more casually and frequently than standard English 'yes'."},
    {"word":"ya lor","type":"phrase","pronunciation":"yah-lor","meaning":"Yes lor \u2014 resigned or obvious agreement. 'Yeah, exactly, what else did you expect?'"},
    {"word":"nah","type":"exclamation / particle","pronunciation":"nah","meaning":"Here, take this. Used when handing something over. Also a resigned 'see lah' when proven right."},
    {"word":"oredi","type":"adverb","pronunciation":"or-reh-dee","meaning":"Already. A Singlish pronunciation of 'already' compressed into two fast syllables."},
    {"word":"walao","type":"exclamation","pronunciation":"wah-lau","meaning":"Expresses shock, disbelief, or exasperation. Can be positive or negative depending on context."},
    {"word":"wah lao eh","type":"exclamation","pronunciation":"wah-lau-eh","meaning":"Stronger exasperation than walao. Used when something is truly unbelievable or outrageous."},
    {"word":"wah lau","type":"exclamation","pronunciation":"wah-lau","meaning":"Shorter form of 'wah lao eh'. Expressing disbelief, exasperation, or mild annoyance."},
    {"word":"wah","type":"exclamation","pronunciation":"wah","meaning":"An exclamation of admiration, surprise, or impressed disbelief. The Singaporean 'wow'."},
    {"word":"alamak","type":"exclamation","pronunciation":"ah-lah-mak","meaning":"Expresses shock, dismay, or exasperation. Similar to 'oh no!' or 'goodness gracious!'"},
    {"word":"aiyo","type":"exclamation","pronunciation":"eye-yoh","meaning":"Expresses dismay, frustration, mild pain, or exasperated sympathy. Very versatile."},
    {"word":"aiyah","type":"exclamation","pronunciation":"eye-yah","meaning":"Longer, more dramatic version of 'aiyo'. Expresses stronger frustration or resigned disappointment."},
    {"word":"aiya","type":"exclamation","pronunciation":"eye-yah","meaning":"Softer version of 'aiyah' \u2014 expressing mild frustration, resignation, or small surprise."},
    {"word":"aiseh","type":"exclamation","pronunciation":"eye-say","meaning":"An impressed or pleasantly surprised exclamation. 'Wow, look at that!' or 'Well, well!'"},
    {"word":"orh hor","type":"exclamation","pronunciation":"or-hor","meaning":"Uh-oh! Used playfully to signal that someone is in trouble, or to tease when they've been caught out."},
    {"word":"orbi good","type":"phrase","pronunciation":"or-bee good","meaning":"Serves you right. Said when someone suffers a consequence they clearly brought on themselves."},
    {"word":"choy","type":"exclamation","pronunciation":"choy","meaning":"Touch wood! Said to ward off bad luck after mentioning something inauspicious. Cantonese origin."},
    {"word":"oi","type":"exclamation","pronunciation":"oi","meaning":"Hey! Used to get someone's attention, express protest, or scold. Rude or casual depending on tone."},
    {"word":"wah piang","type":"exclamation","pronunciation":"wah-pee-ang","meaning":"A stronger exclamation of shock or exasperation. 'Oh my goodness' but distinctly Singaporean."},
    {"word":"hah","type":"exclamation / particle","pronunciation":"hah","meaning":"What? Expresses disbelief or that you didn't hear properly. Also a challenging 'excuse me?'"},
    {"word":"wa seh","type":"exclamation","pronunciation":"wah-say","meaning":"Wow, impressive! Hokkien expression of admiration or surprised delight. Stronger than plain 'wah'."},
    {"word":"wah seh","type":"exclamation","pronunciation":"wah-say","meaning":"Alternate spelling of 'wa seh'. Wow \u2014 an astonished, impressed exclamation."},
    {"word":"wah eh","type":"exclamation","pronunciation":"wah-ay","meaning":"A variant of 'wah' with added 'eh' for more emphasis. Stronger surprised admiration."},
    {"word":"wah seh beh","type":"exclamation","pronunciation":"wah-say-bay","meaning":"A drawn-out impressed exclamation, even stronger than 'wa seh'. Expresses peak admiration."},
    {"word":"siao","type":"adjective / exclamation","pronunciation":"see-ow","meaning":"Crazy, mad, or nuts. Can describe a person, idea, or situation that is wild or unbelievable."},
    {"word":"huat ah","type":"exclamation","pronunciation":"hoo-at ah","meaning":"A Hokkien cheer for prosperity and good fortune, especially popular around Chinese New Year."},
    {"word":"nabeh","type":"exclamation","pronunciation":"nah-bay","meaning":"A Hokkien expletive expressing strong frustration or disbelief. Use with care \u2014 quite strong."},
    {"word":"shiok","type":"adjective / exclamation","pronunciation":"shee-ok","meaning":"Extremely good, satisfying, or pleasurable \u2014 especially used for food or enjoyable experiences."},
    {"word":"kiasu","type":"adjective","pronunciation":"kee-ah-soo","meaning":"Fear of losing out. Overly competitive or selfish, driven by anxiety about missing opportunities."},
    {"word":"kiasi","type":"adjective","pronunciation":"kee-ah-see","meaning":"Fear of death or harm. Describes someone who is overly cautious, timid, or easily scared."},
    {"word":"kiasee","type":"adjective","pronunciation":"kee-ah-see","meaning":"Alternate spelling of 'kiasi'. Fearful of harm, overly cautious or timid."},
    {"word":"atas","type":"adjective","pronunciation":"ah-tas","meaning":"High-class, posh, or snobbish. Describes people, places, or things that are fancy or elitist."},
    {"word":"blur","type":"adjective","pronunciation":"blur","meaning":"Confused, clueless, or unaware of what's going on. Often extended to 'blur like sotong'."},
    {"word":"sian","type":"adjective / exclamation","pronunciation":"see-en","meaning":"Bored, tired, or fed up. Expresses weariness, dread, or resigned exhaustion."},
    {"word":"swee","type":"adjective","pronunciation":"swee","meaning":"Pretty, beautiful, or perfectly executed. Used for appearance and for neatly done outcomes."},
    {"word":"chio","type":"adjective","pronunciation":"chee-oh","meaning":"Very attractive or pretty. Usually used for a girl \u2014 a high compliment in Singlish."},
    {"word":"steady","type":"adjective / exclamation","pronunciation":"steady","meaning":"Reliable, impressive, or dependable. Used as high praise for someone's abilities or character."},
    {"word":"solid","type":"adjective","pronunciation":"solid","meaning":"Excellent, reliable, or impressive. Similar to 'steady' \u2014 high praise for quality or performance."},
    {"word":"power","type":"adjective","pronunciation":"power","meaning":"Impressive, amazing, or highly capable. High praise for someone's abilities or achievements."},
    {"word":"tok kong","type":"adjective","pronunciation":"tok kong","meaning":"The best, top-quality, or excellent. The highest possible praise for something or someone."},
    {"word":"happening","type":"adjective","pronunciation":"happening","meaning":"Lively, fun, exciting, and full of energy. Used to describe vibrant places or people."},
    {"word":"paiseh","type":"adjective / exclamation","pronunciation":"pie-say","meaning":"Feeling embarrassed, shy, or ashamed. Also used as a casual apology for minor inconveniences."},
    {"word":"action","type":"adjective","pronunciation":"action","meaning":"Showing off, arrogant, or acting above one's station. Used to call out pretentious behaviour."},
    {"word":"hao lian","type":"adjective","pronunciation":"hao lee-en","meaning":"Boastful or showing off. Someone who can't resist bragging about their achievements."},
    {"word":"bodoh","type":"adjective","pronunciation":"boh-doh","meaning":"Stupid or foolish. Borrowed from Malay \u2014 used as mild insult or self-deprecating humour."},
    {"word":"gila","type":"adjective / exclamation","pronunciation":"gee-lah","meaning":"Crazy, wild, or intense. Borrowed from Malay \u2014 used to describe something extreme or unbelievable."},
    {"word":"garang","type":"adjective","pronunciation":"gah-rang","meaning":"Fierce, tough, or brave in a positive way. Someone who is bold and gives their all."},
    {"word":"kaypoh","type":"adjective / noun","pronunciation":"kay-poh","meaning":"Nosy or busybody. Someone who pries into other people's business unnecessarily."},
    {"word":"cheem","type":"adjective","pronunciation":"cheem","meaning":"Deep, profound, or overly complicated. Used for things that are hard to understand intellectually."},
    {"word":"chim","type":"adjective","pronunciation":"chim","meaning":"Variant spelling of 'cheem'. Deep, profound, or intellectually demanding."},
    {"word":"wayang","type":"verb / noun / adjective","pronunciation":"wah-yang","meaning":"To put on a show or pretend. Doing something for appearances rather than genuine sincerity."},
    {"word":"kan cheong","type":"adjective","pronunciation":"kan-cheong","meaning":"Nervous, anxious, flustered, or stressed. Describes someone who panics easily."},
    {"word":"cincai","type":"adjective / adverb","pronunciation":"chin-chai","meaning":"Anything will do; done carelessly or without much preference. Casual indifference."},
    {"word":"anyhow","type":"adverb","pronunciation":"any-how","meaning":"Carelessly or randomly, without proper thought or method. Often used as mild scolding."},
    {"word":"suay","type":"adjective","pronunciation":"swai","meaning":"Unlucky. Describes someone who has bad luck or a situation where things go wrong by chance."},
    {"word":"jio","type":"verb","pronunciation":"jee-oh","meaning":"To invite someone along. From Hokkien \u2014 universally used across all communities in Singapore."},
    {"word":"chiong","type":"verb / adjective","pronunciation":"chee-ong","meaning":"To rush, charge at something, or go all-out with full energy and commitment."},
    {"word":"sibei","type":"adverb","pronunciation":"see-bay","meaning":"Very, extremely. A Hokkien intensifier \u2014 stronger than 'very', widely used everywhere."},
    {"word":"pek chek","type":"adjective","pronunciation":"pek-chek","meaning":"Frustrated, annoyed, stressed, or exasperated. The Hokkien word for feeling fed up."},
    {"word":"bochup","type":"adjective / verb","pronunciation":"boh-chup","meaning":"Don't care, indifferent, couldn't be bothered. Hokkien for not minding something at all."},
    {"word":"bo chap","type":"adjective","pronunciation":"boh-chap","meaning":"Alternate form of 'bochup' \u2014 completely indifferent, cannot be bothered."},
    {"word":"ho seh","type":"adjective / exclamation","pronunciation":"hoh-say","meaning":"Doing well, great, excellent. A Hokkien expression of approval or things going smoothly."},
    {"word":"ho liao","type":"phrase","pronunciation":"hoh-lee-ow","meaning":"Good enough, well done, that's fine. Hokkien expression of mild satisfaction or completion."},
    {"word":"simi sai","type":"phrase","pronunciation":"see-mee sigh","meaning":"What nonsense is this? What rubbish? A Hokkien rhetorical question expressing frustration."},
    {"word":"simi da ji","type":"phrase","pronunciation":"see-mee dah-jee","meaning":"What is going on here, what's the matter? A Hokkien rhetorical question about the situation."},
    {"word":"mai","type":"verb","pronunciation":"my","meaning":"Don't, don't want to, or don't do that. Hokkien negative \u2014 common alternative to 'don't'."},
    {"word":"hiam","type":"adjective","pronunciation":"hee-am","meaning":"Fussy, picky, or hard to please \u2014 especially about food or fine details. Hokkien origin."},
    {"word":"tio","type":"verb","pronunciation":"tee-oh","meaning":"To get, receive, or encounter something \u2014 usually good or neutral. Hokkien origin."},
    {"word":"tiok","type":"adjective / exclamation","pronunciation":"tee-ok","meaning":"Correct, right, that's it. From Hokkien/Teochew \u2014 used to affirm that something is accurate."},
    {"word":"buay song","type":"phrase","pronunciation":"boo-ay song","meaning":"Unhappy, dissatisfied, or harbouring negative feelings about a person or situation."},
    {"word":"buay sai","type":"phrase","pronunciation":"boo-ay sigh","meaning":"Cannot, unacceptable, or not allowed. Hokkien way to say something is not possible or not okay."},
    {"word":"buay hiao","type":"phrase","pronunciation":"boo-ay hee-ow","meaning":"Don't know how to, or lacking the skill to do something properly. From Hokkien."},
    {"word":"buay pai","type":"phrase","pronunciation":"boo-ay pie","meaning":"Not bad, quite good. An understated compliment \u2014 typical Singapore understatement."},
    {"word":"buay hao","type":"phrase","pronunciation":"boo-ay how","meaning":"Not good, no good. The Hokkien way to say something is bad or unsatisfactory."},
    {"word":"siam","type":"verb","pronunciation":"see-am","meaning":"To dodge, avoid, or get out of the way. Used both literally and for avoiding responsibilities."},
    {"word":"bo bian","type":"phrase","pronunciation":"boh bee-an","meaning":"No choice, nothing can be done about it. A Hokkien expression of resigned acceptance."},
    {"word":"swaku","type":"adjective / noun","pronunciation":"swah-koo","meaning":"Unsophisticated, out of touch, naive, or not up with trends. A country bumpkin."},
    {"word":"gong","type":"adjective","pronunciation":"gong","meaning":"Stupid, foolish, or dimwitted. Cantonese origin \u2014 used affectionately or critically."},
    {"word":"sian diao","type":"phrase","pronunciation":"see-en dee-ow","meaning":"Completely defeated, utterly sian. Intensified version implying total mental depletion."},
    {"word":"jiak kentang","type":"phrase","pronunciation":"jee-ak ken-tang","meaning":"Literally 'eat potato' \u2014 describes a Singaporean who is overly westernised and lost touch with local culture."},
    {"word":"jiak ba buay","type":"phrase","pronunciation":"jee-ak bah boo-ay","meaning":"Eaten until full and completely satisfied. Hokkien expression for post-meal contentment."},
    {"word":"hantam","type":"verb","pronunciation":"han-tam","meaning":"To hit, beat, or attack. Also used figuratively: just do it boldly without overthinking."},
    {"word":"tok tok chen","type":"phrase","pronunciation":"tok-tok-chen","meaning":"To talk nonsense, ramble meaninglessly, or say things without basis. From Hokkien."},
    {"word":"steady bom pi pi","type":"phrase","pronunciation":"steady bom pi pi","meaning":"An emphatic version of 'steady' \u2014 absolutely excellent or impressive. Extra syllables add flair."},
    {"word":"steady pom pee pee","type":"phrase","pronunciation":"steady pom pee pee","meaning":"Alternate spelling of 'steady bom pi pi'. Absolutely excellent \u2014 same energy, different spelling."},
    {"word":"lim kopi","type":"phrase","pronunciation":"lim koh-pee","meaning":"Literally 'drink coffee'. Singapore euphemism for being called in by the police for questioning."},
    {"word":"zao","type":"verb","pronunciation":"zow","meaning":"To run away, flee, or leave quickly. Used when someone escapes or exits a situation fast."},
    {"word":"pai kia","type":"noun / adjective","pronunciation":"pie-kia","meaning":"A gangster, troublemaker, or bad boy. From Hokkien 'bad child' \u2014 often used affectionately."},
    {"word":"lao jiao","type":"noun / adjective","pronunciation":"lao jee-ow","meaning":"An experienced veteran or old hand. Literally 'old bird' in Hokkien."},
    {"word":"chek ark","type":"exclamation / adjective","pronunciation":"chek-ark","meaning":"Cringe, embarrassing, or face-palm worthy. Hokkien expression for when something is awkward."},
    {"word":"piah","type":"verb / exclamation","pronunciation":"pee-ah","meaning":"To work hard, push through, grind. Also used as an exclamation when exerting great effort."},
    {"word":"chao","type":"adjective","pronunciation":"chow","meaning":"Smelly, bad, or terrible. Hokkien origin \u2014 used for unpleasant smells and by extension bad quality."},
    {"word":"sia suay","type":"phrase","pronunciation":"see-ah swai","meaning":"Embarrassing, disgraceful, or a loss of face. Hokkien for bringing shame upon yourself."},
    {"word":"zao geng","type":"phrase","pronunciation":"zow-geng","meaning":"To fake illness or injury to avoid work or duties. NS slang \u2014 now used broadly."},
    {"word":"jiak zua","type":"phrase","pronunciation":"jee-ak zua","meaning":"To eat snake; to slack off or avoid doing work while pretending to be busy."},
    {"word":"kena","type":"verb","pronunciation":"keh-nah","meaning":"To get hit by, suffer, or receive something \u2014 usually bad. A Malay word central to Singlish."},
    {"word":"boleh","type":"adjective / exclamation","pronunciation":"boh-lay","meaning":"Can, yes, or capable. From Malay \u2014 used to express ability, agreement, or encouragement."},
    {"word":"habis","type":"adjective / exclamation","pronunciation":"hah-bis","meaning":"Finished, all gone, done for. From Malay \u2014 means 'sold out', 'over', or 'we're in trouble'."},
    {"word":"lagi","type":"adverb","pronunciation":"lah-ghee","meaning":"Even more, still more, additionally. From Malay \u2014 used to intensify or add to a point."},
    {"word":"mati","type":"adjective / exclamation","pronunciation":"mah-tee","meaning":"Dead, finished, or in deep trouble. From Malay \u2014 used figuratively when things go very wrong."},
    {"word":"tipu","type":"verb","pronunciation":"tee-poo","meaning":"To cheat, lie, or deceive. From Malay \u2014 used casually for anything from white lies to scams."},
    {"word":"senang","type":"adjective","pronunciation":"seh-nang","meaning":"Easy, comfortable, or at ease. From Malay \u2014 the opposite of 'susah'. Blissfully effortless."},
    {"word":"susah","type":"adjective","pronunciation":"soo-sah","meaning":"Difficult, troublesome, or hard. From Malay \u2014 used for both physical hardship and life challenges."},
    {"word":"cepat","type":"adverb / adjective","pronunciation":"cheh-pat","meaning":"Fast, quickly, hurry up. From Malay \u2014 used to urge speed or describe something swift."},
    {"word":"bagus","type":"adjective / exclamation","pronunciation":"bah-goos","meaning":"Good, excellent, well done. From Malay \u2014 used as straightforward praise."},
    {"word":"sama sama","type":"phrase","pronunciation":"sah-mah sah-mah","meaning":"The same, equal, or you're welcome. From Malay \u2014 for similarity or as a reciprocal response."},
    {"word":"mana tau","type":"phrase","pronunciation":"mah-nah tau","meaning":"Who would have thought? Who knew? Expresses surprise at an unexpected outcome."},
    {"word":"jangan","type":"verb","pronunciation":"jah-ngan","meaning":"Don't, do not. From Malay \u2014 used more emphatically than 'mai' or standard 'don't'."},
    {"word":"tolong","type":"verb / exclamation","pronunciation":"toh-long","meaning":"Please help, please. From Malay \u2014 used as a genuine plea or sarcastically when exasperated."},
    {"word":"tapao","type":"verb / noun","pronunciation":"tah-pow","meaning":"To take food away (takeaway). Also spelled 'dabao'. The Singapore way to say take-out."},
    {"word":"dabao","type":"verb / noun","pronunciation":"dah-bow","meaning":"To take food away (takeaway). Alternate spelling of 'tapao'. Equally common in usage."},
    {"word":"lobang","type":"noun","pronunciation":"loh-bang","meaning":"A good deal, opportunity, or insider contact. Literally 'hole' in Malay \u2014 a useful opening."},
    {"word":"suka suka","type":"phrase","pronunciation":"soo-kah soo-kah","meaning":"As you like, however you want, at your own whim. From Malay 'suka' (to like)."},
    {"word":"pantang","type":"adjective / noun","pronunciation":"pan-tang","meaning":"Taboo, forbidden by superstition, or having strong personal rules about something."},
    {"word":"sayang","type":"adjective / exclamation","pronunciation":"sah-yang","meaning":"A pity, what a waste. From Malay \u2014 used to express that something is regrettably lost or spoiled."},
    {"word":"mesti","type":"verb","pronunciation":"mes-tee","meaning":"Must, have to, definitely. From Malay \u2014 used to express strong obligation or certainty."},
    {"word":"pusing","type":"adjective / verb","pronunciation":"poo-sing","meaning":"Dizzy, confused, going round in circles. From Malay 'pusing' (to spin)."},
    {"word":"terbalik","type":"adjective / adverb","pronunciation":"ter-bah-lik","meaning":"Upside down, reversed, backwards, or inside out. From Malay."},
    {"word":"takpe","type":"phrase","pronunciation":"tak-pay","meaning":"Never mind, it's okay, no worries. From Malay 'tak apa' \u2014 used to dismiss concerns."},
    {"word":"betul","type":"adjective / exclamation","pronunciation":"beh-tul","meaning":"Correct, true, right. From Malay \u2014 used to confirm or affirm something is accurate."},
    {"word":"malu","type":"adjective","pronunciation":"mah-loo","meaning":"Embarrassed, shy, or ashamed. From Malay \u2014 similar to 'paiseh' but often deeper."},
    {"word":"kuat","type":"adjective","pronunciation":"koo-at","meaning":"Strong, powerful, or intense. From Malay \u2014 used for physical or metaphorical strength."},
    {"word":"sedap","type":"adjective","pronunciation":"seh-dap","meaning":"Delicious, tasty, very good to eat. From Malay \u2014 the ultimate compliment for food."},
    {"word":"jelak","type":"adjective","pronunciation":"jeh-lak","meaning":"Sick of something from too much of it, especially food. Feeling cloyed from excess."},
    {"word":"heng","type":"adjective / exclamation","pronunciation":"heng","meaning":"Lucky, fortunate. A Hokkien word widely used to express relief at a good outcome."},
    {"word":"gostan","type":"verb","pronunciation":"goh-stan","meaning":"To reverse or go backwards. Derived from the nautical 'go astern'. Used for vehicles and figuratively."},
    {"word":"machiam","type":"adverb","pronunciation":"mah-chee-am","meaning":"Like, similar to, as if. Used to draw comparisons or describe something metaphorically."},
    {"word":"lepak","type":"verb / noun","pronunciation":"leh-pak","meaning":"To hang out, lounge around, or relax aimlessly. A chill, purposeless, stress-free gathering."},
    {"word":"makan","type":"verb / noun","pronunciation":"mah-kan","meaning":"To eat, or a meal. Borrowed from Malay \u2014 universally understood across all communities."},
    {"word":"vetti","type":"adjective","pronunciation":"veh-tee","meaning":"Free, idle, having nothing to do. Tamil origin \u2014 describes someone with time to spare."},
    {"word":"macha","type":"noun","pronunciation":"mah-cha","meaning":"Buddy, friend, bro. Tamil origin \u2014 a warm, casual term of address for a close friend."},
    {"word":"chope","type":"verb","pronunciation":"chope","meaning":"To reserve or claim a seat or spot, typically by placing tissue packets or an item on it."},
    {"word":"sabo","type":"verb","pronunciation":"sah-bo","meaning":"To sabotage someone, often playfully. Deliberately putting a person in an awkward position."},
    {"word":"tekan","type":"verb","pronunciation":"teh-kan","meaning":"To bully, pressure, or drill someone hard. Often used in NS or tough training contexts."},
    {"word":"arrow","type":"verb","pronunciation":"arrow","meaning":"To assign a task to someone, usually without consent. Being voluntold for a job."},
    {"word":"stone","type":"verb","pronunciation":"stone","meaning":"To space out, zone out, or stare blankly at nothing. Completely checked out mentally."},
    {"word":"send","type":"verb","pronunciation":"send","meaning":"To send or accompany someone to a destination. Singlish replaces 'drive/take/accompany'."},
    {"word":"burn","type":"verb","pronunciation":"burn","meaning":"To spend lavishly, show off expensive things, or waste money on unnecessary luxuries."},
    {"word":"slack","type":"verb / adjective","pronunciation":"slack","meaning":"To relax, take it easy, or have an enjoyably stress-free time. A much-needed break."},
    {"word":"uncle","type":"noun","pronunciation":"uncle","meaning":"Term of address for older men regardless of relation. Used for taxi drivers, hawker stall owners."},
    {"word":"auntie","type":"noun","pronunciation":"auntie","meaning":"Term of address for older women regardless of relation. Warm and neutral."},
    {"word":"limpeh","type":"pronoun","pronunciation":"lim-peh","meaning":"A boastful first-person pronoun meaning 'I' or 'your father'. Used to assert authority or brag."},
    {"word":"ownself","type":"pronoun","pronunciation":"own-self","meaning":"Yourself, by yourself. Often in the phrase 'ownself check ownself' \u2014 self-accountability."},
    {"word":"gahmen","type":"noun","pronunciation":"gah-men","meaning":"The government. A distinctly Singlish rendering of 'government' in a local accent."},
    {"word":"towkay","type":"noun","pronunciation":"tow-kay","meaning":"A boss, business owner, or wealthy businessman. Hokkien origin \u2014 used respectfully or ironically."},
    {"word":"angmoh","type":"noun / adjective","pronunciation":"ang-moh","meaning":"A Caucasian or Western person. Literally 'red hair' in Hokkien. Used descriptively."},
    {"word":"sinkie","type":"noun","pronunciation":"sink-ee","meaning":"A Singaporean local \u2014 sometimes used self-deprecatingly by Singaporeans about themselves."},
    {"word":"heartlander","type":"noun","pronunciation":"heart-lander","meaning":"A Singaporean who lives in HDB estates and embodies typical local working-class values."},
    {"word":"ah beng","type":"noun / adjective","pronunciation":"ah-beng","meaning":"A stereotypical working-class Singaporean Chinese young man \u2014 loud fashion, thick accent. Affectionate."},
    {"word":"ah lian","type":"noun / adjective","pronunciation":"ah-lee-an","meaning":"A stereotypical working-class Singaporean Chinese young woman. Female counterpart of 'ah beng'."},
    {"word":"drama mama","type":"noun","pronunciation":"drama mama","meaning":"A dramatic person who overreacts or turns small issues into big scenes."},
    {"word":"kancheong spider","type":"phrase","pronunciation":"kan-cheong spider","meaning":"An extremely anxious or flustered person. Intensified 'kan cheong' with comic emphasis."},
    {"word":"sabo king","type":"noun","pronunciation":"sah-bo king","meaning":"Someone who is a master saboteur \u2014 always volunteering others or putting friends in spots."},
    {"word":"blur queen","type":"noun / phrase","pronunciation":"blur queen","meaning":"A person who is perpetually clueless or scattered. A title for someone chronically 'blur'."},
    {"word":"simi","type":"pronoun / exclamation","pronunciation":"see-mee","meaning":"What? From Hokkien 'what'. Used to question or express disbelief at what was just said."},
    {"word":"kopitiam","type":"noun","pronunciation":"koh-pee-tee-am","meaning":"A traditional coffee shop serving local food and drinks. The social heart of Singapore neighbourhoods."},
    {"word":"pasar malam","type":"noun","pronunciation":"pah-sar mah-lam","meaning":"Night market. A temporary outdoor market with hawker food, games, and goods \u2014 very festive."},
    {"word":"void deck","type":"noun","pronunciation":"void deck","meaning":"The open ground floor of Singapore HDB blocks, used as communal space for gatherings."},
    {"word":"cai png","type":"noun","pronunciation":"chye-png","meaning":"Economy rice. Pick-your-own-dishes over white rice \u2014 affordable, fast, and satisfying."},
    {"word":"kopi-O","type":"noun","pronunciation":"koh-pee-oh","meaning":"Black coffee with sugar, Singapore-style. 'O' means black in Hokkien. Part of the local kopi code."},
    {"word":"teh tarik","type":"noun","pronunciation":"teh tah-rik","meaning":"Pulled tea \u2014 milk tea stretched between two cups to create froth. A Malaysian and Singaporean icon."},
    {"word":"char siew","type":"noun","pronunciation":"char-shew","meaning":"Cantonese BBQ pork \u2014 caramelised, tender, sweet-savoury. A flagship protein at hawker stalls."},
    {"word":"prata","type":"noun","pronunciation":"prah-tah","meaning":"Roti prata \u2014 flaky flatbread cooked on a hot griddle, served with curry or sugar. A 24-hour staple."},
    {"word":"mee goreng","type":"noun","pronunciation":"mee goh-reng","meaning":"Spicy Indian-style fried noodles \u2014 a Singapore hawker classic with thick tomato-chilli base."},
    {"word":"satay","type":"noun","pronunciation":"sah-tay","meaning":"Grilled skewered meat served with peanut sauce, cucumber, and onions. A barbecue icon."},
    {"word":"zi char","type":"noun","pronunciation":"tzee-char","meaning":"Cooked-to-order Chinese dishes at hawker stalls. Like a casual Chinese kitchen \u2014 very communal."},
    {"word":"bak kut teh","type":"noun","pronunciation":"bak-kut-tay","meaning":"Pork rib soup \u2014 slow-cooked in herbal or peppery broth. A classic breakfast or supper dish."},
    {"word":"char kway teow","type":"noun","pronunciation":"char-kwee-tee-oh","meaning":"Fried flat rice noodles with cockles, egg, chye sim, and char siew. A beloved hawker dish."},
    {"word":"nasi lemak","type":"noun","pronunciation":"nah-see leh-mak","meaning":"Coconut rice with sambal, fried anchovies, peanuts, and a boiled egg. A national treasure."},
    {"word":"laksa","type":"noun","pronunciation":"lak-sah","meaning":"Spicy coconut milk noodle soup \u2014 Singapore's most iconic and passionately debated dish."},
    {"word":"otah","type":"noun","pronunciation":"oh-tah","meaning":"Spiced fish paste grilled in banana leaf \u2014 a smoky, fragrant Malay-origin hawker snack."},
    {"word":"ice kachang","type":"noun","pronunciation":"ice kah-chang","meaning":"Shaved ice dessert piled with colourful syrup, red beans, attap chee, and condensed milk."},
    {"word":"wonton mee","type":"noun","pronunciation":"won-ton mee","meaning":"Egg noodles served with wontons, char siew, and a dark soy-based sauce. A beloved classic."},
    {"word":"yum cha","type":"verb / noun","pronunciation":"yum-cha","meaning":"To go for dim sum and tea. Cantonese origin \u2014 a leisurely meal that doubles as a social outing."},
    {"word":"rojak","type":"adjective / noun","pronunciation":"roh-jak","meaning":"Mixed, messy, or a diverse blend of things. Literally a popular salad of mixed ingredients."},
    {"word":"five Cs","type":"phrase","pronunciation":"five Cs","meaning":"Cash, Car, Condo, Credit Card, Country Club. The traditional Singaporean aspirational checklist."},
    {"word":"cham","type":"adjective / exclamation","pronunciation":"cham","meaning":"In trouble, pitiful, or in a difficult situation. Expresses sympathy for someone in a bad spot."},
    {"word":"bojio","type":"phrase","pronunciation":"boh-jee-oh","meaning":"Alternate spelling of 'bo jio' \u2014 didn't invite. Used when you feel left out of a gathering."},
    {"word":"bo jio","type":"phrase","pronunciation":"boh jee-oh","meaning":"Didn't invite. Used to express mock-offence or genuine hurt at being left out of an outing."},
    {"word":"bo liao","type":"adjective / phrase","pronunciation":"boh lee-ao","meaning":"Nothing better to do; bored; pointless or silly. Describes idle behaviour or a waste of time."},
    {"word":"buay tahan","type":"phrase","pronunciation":"boo-ay tah-han","meaning":"Can't stand it; unable to endure something. Used to express that something is completely unbearable."},
    {"word":"buay paiseh","type":"phrase","pronunciation":"boo-ay pie-say","meaning":"Shameless or thick-skinned. Not embarrassed when one clearly should be."},
    {"word":"can or not","type":"phrase","pronunciation":"can or not","meaning":"Asking whether something is possible or acceptable. 'Is that okay?' or 'Can you do it?'"},
    {"word":"catch no ball","type":"phrase","pronunciation":"catch no ball","meaning":"Completely unable to understand what someone is saying. Derived from a football metaphor."},
    {"word":"chao kuan","type":"adjective","pronunciation":"chow kwan","meaning":"Extremely stingy or miserly. Describes someone who is excessively tight with money."},
    {"word":"confirm plus chop","type":"phrase","pronunciation":"confirm plus chop","meaning":"Absolutely certain, with zero doubt. The 'chop' metaphorically adds an official rubber stamp."},
    {"word":"dun play play","type":"phrase","pronunciation":"dun play play","meaning":"Don't underestimate this; take it seriously. A warning that something is more serious than it looks."},
    {"word":"last time","type":"phrase","pronunciation":"last time","meaning":"In the past. Used nostalgically to contrast how things used to be versus now."},
    {"word":"liddat","type":"adverb","pronunciation":"lih-dat","meaning":"Like that. A contracted casual form describing a manner, situation, or way of doing things."},
    {"word":"long long ago","type":"phrase","pronunciation":"long long ago","meaning":"A very long time ago. The repetition of 'long' adds nostalgic, storytelling emphasis."},
    {"word":"on lah","type":"phrase","pronunciation":"on lah","meaning":"Agreed, yes, let's do it! A casual and enthusiastic way to confirm or commit to a plan."},
    {"word":"on the ball","type":"phrase","pronunciation":"on the ball","meaning":"Alert, competent, and on top of things. Someone who is sharp and always pays attention."},
    {"word":"one kind","type":"phrase","pronunciation":"one kind","meaning":"Strange, peculiar, or different from the norm. A mild, non-offensive way to say something is odd."},
    {"word":"potong jalan","type":"phrase","pronunciation":"poh-tong jah-lan","meaning":"To cut in on someone, especially to steal a romantic interest or opportunity from a friend."},
    {"word":"shiok sendiri","type":"phrase","pronunciation":"shee-ok sen-dee-ree","meaning":"To enjoy or please only yourself, indulging in something purely for your own satisfaction."},
    {"word":"sian half","type":"phrase","pronunciation":"see-en half","meaning":"Extremely bored or fed up. An intensified version of 'sian' for when regular sian isn't enough."},
    {"word":"jialat","type":"adjective / exclamation","pronunciation":"jee-ah-lat","meaning":"A serious or dire situation. Expresses that something is bad, troublesome, or has gone wrong."},
    {"word":"jialat jialat","type":"phrase","pronunciation":"jee-ah-lat jee-ah-lat","meaning":"An intensified version of jialat \u2014 really, truly dire. Repetition emphasises how bad things are."},
    {"word":"die die","type":"phrase","pronunciation":"die die","meaning":"No matter what, at all costs, absolutely must. Expresses unwavering commitment despite obstacles."},
    {"word":"where got","type":"phrase","pronunciation":"where got","meaning":"How can that be true? There's no such thing! Used to deny or dispute a claim strongly."},
    {"word":"how can","type":"phrase","pronunciation":"how can","meaning":"That's not acceptable! How is that possible? Expresses indignation or disbelief."},
    {"word":"give chance","type":"phrase","pronunciation":"give chance","meaning":"Give a break, show mercy, ease up. A plea for leniency or for someone to lower their expectations."},
    {"word":"see first","type":"phrase","pronunciation":"see first","meaning":"Wait and see, let me consider it first. A non-committal response buying time before deciding."},
    {"word":"act blur","type":"phrase","pronunciation":"act blur","meaning":"To pretend not to know or understand something when you actually do. Strategic ignorance."},
    {"word":"act cute","type":"phrase","pronunciation":"act cute","meaning":"To behave in a coy, sweet, or overly adorable way to get sympathy or attention."},
    {"word":"act innocent","type":"phrase","pronunciation":"act innocent","meaning":"To pretend you have no idea what happened or what someone is talking about."},
    {"word":"talk cock","type":"phrase","pronunciation":"talk cock","meaning":"To talk nonsense, speak without basis, or have meaningless chit-chat."},
    {"word":"half past six","type":"phrase","pronunciation":"half past six","meaning":"Mediocre, sub-standard, or poorly done. Something done half-heartedly without proper effort."},
    {"word":"eat wind","type":"phrase","pronunciation":"eat wind","meaning":"To travel or go on holiday. Literally 'eat wind' \u2014 leisurely breathing fresh air elsewhere."},
    {"word":"no eye see","type":"phrase","pronunciation":"no eye see","meaning":"Cannot bear to look; too embarrassing or cringeworthy to watch."},
    {"word":"give face","type":"phrase","pronunciation":"give face","meaning":"To show respect, be polite, or avoid embarrassing someone publicly."},
    {"word":"lose face","type":"phrase","pronunciation":"lose face","meaning":"To be publicly embarrassed or humiliated. Losing social standing or dignity in front of others."},
    {"word":"thick skin","type":"phrase","pronunciation":"thick skin","meaning":"Shameless, not easily embarrassed, unaffected by criticism. Can be admiring or critical."},
    {"word":"so how","type":"phrase","pronunciation":"so how","meaning":"So what do we do now? What's the plan? Used to prompt a decision or next step."},
    {"word":"then how","type":"phrase","pronunciation":"then how","meaning":"Then what? What happens next? Used to question the consequence of a situation."},
    {"word":"try try see","type":"phrase","pronunciation":"try try see","meaning":"Give it a try and see what happens. A casual, low-pressure encouragement to attempt something."},
    {"word":"can make it","type":"phrase","pronunciation":"can make it","meaning":"Able to succeed, manage, or arrive in time. An assessment of whether something is achievable."},
    {"word":"cannot make it","type":"phrase","pronunciation":"cannot make it","meaning":"Unable to succeed, attend, or manage. Something is beyond reach or ability."},
    {"word":"one shot","type":"phrase","pronunciation":"one shot","meaning":"In one try, all at once, in a single effort. Completing something without multiple attempts."},
    {"word":"chop chop","type":"phrase","pronunciation":"chop chop","meaning":"Hurry up, quickly, get moving. An urgent call to speed things up immediately."},
    {"word":"add oil","type":"phrase","pronunciation":"add oil","meaning":"You can do it! Keep going! Direct translation of Cantonese 'gaa yau' \u2014 an encouragement cheer."},
    {"word":"jia you","type":"phrase","pronunciation":"jia you","meaning":"Come on! You can do it! Keep going! A Mandarin encouragement cheer widely used in Singapore."},
    {"word":"sure bo","type":"phrase","pronunciation":"sure boh","meaning":"Are you sure? Really? An expression of mild disbelief asking for confirmation."},
    {"word":"zhun","type":"adjective","pronunciation":"zhoon","meaning":"Accurate, precise, spot-on. Describes something that is exactly right or perfectly timed."},
    {"word":"zhun bo","type":"phrase","pronunciation":"zhoon boh","meaning":"Is it accurate? Is that right? Checking whether a claim or detail is actually correct."},
    {"word":"on or not","type":"phrase","pronunciation":"on or not","meaning":"Are you in? Are you up for it? A casual way to confirm if someone wants to join a plan."},
    {"word":"on already","type":"phrase","pronunciation":"on already","meaning":"It's decided, confirmed, and ready to go. A done deal \u2014 fully locked in."},
    {"word":"also can","type":"phrase","pronunciation":"also can","meaning":"That works too, that's also acceptable. Expresses flexible agreement with an alternative."},
    {"word":"also never mind","type":"phrase","pronunciation":"also never mind","meaning":"That's also fine, no problem with that either. Flexible, easy-going acceptance of alternatives."},
    {"word":"never","type":"verb (auxiliary)","pronunciation":"never","meaning":"Didn't, did not. In Singlish, 'never' replaces 'didn't' as the standard past tense negative."},
    {"word":"got","type":"verb (auxiliary)","pronunciation":"got","meaning":"Have, has, or there is/are. In Singlish, 'got' replaces 'have/has' and 'there is'."},
    {"word":"bao ka liao","type":"phrase","pronunciation":"bao-kah-lee-ow","meaning":"All-inclusive, everything covered, the whole package. Literally 'wrap everything included'."},
    {"word":"look see look see","type":"phrase","pronunciation":"look see look see","meaning":"To browse or wander around without a specific purpose. Casual window shopping or exploring."},
    {"word":"wait long long","type":"phrase","pronunciation":"wait long long","meaning":"Wait forever, will never happen. Used sarcastically to suggest something is not going to come."},
    {"word":"shiok max","type":"phrase","pronunciation":"shee-ok max","meaning":"The maximum level of shiok \u2014 the most satisfying, pleasurable experience possible."},
    {"word":"power lah","type":"phrase","pronunciation":"power lah","meaning":"That's amazing, impressive. Emphatic version of 'power' with the lah particle for extra effect."},
    {"word":"power max","type":"phrase","pronunciation":"power max","meaning":"At maximum power, absolutely the most impressive something can be."},
    {"word":"power sia","type":"phrase","pronunciation":"power see-ah","meaning":"That's extremely impressive. Combining 'power' with 'sia' for extra excited emphasis."},
    {"word":"power one","type":"phrase","pronunciation":"power one","meaning":"That's really impressive. Adding 'one' as an emphatic particle after 'power' to assert the fact."},
    {"word":"very the","type":"phrase","pronunciation":"very the","meaning":"Very, extremely. An intensifier combining 'very' with the Malay 'the' for extra emphasis."},
    {"word":"sibei shiok","type":"phrase","pronunciation":"see-bay shee-ok","meaning":"Extremely shiok. Combining the Hokkien intensifier 'sibei' with 'shiok' for maximum delight."},
    {"word":"sibei power","type":"phrase","pronunciation":"see-bay power","meaning":"Extremely impressive. The Hokkien intensifier 'sibei' amplifying 'power' to maximum."},
    {"word":"sibei sian","type":"phrase","pronunciation":"see-bay see-en","meaning":"Extremely bored or fed up. The Hokkien intensifier 'sibei' amplifying 'sian' to maximum."},
    {"word":"confirm can","type":"phrase","pronunciation":"confirm can","meaning":"Definitely possible, absolutely will work. An assertive guarantee something is achievable."},
    {"word":"confirm siao","type":"phrase","pronunciation":"confirm see-ow","meaning":"Definitely crazy, absolutely insane. Used to describe something outrageously unreasonable."},
    {"word":"confirm or not","type":"phrase","pronunciation":"confirm or not","meaning":"Are you sure? Is this definite? Seeking reassurance that something is locked in."},
    {"word":"no need lah","type":"phrase","pronunciation":"no need lah","meaning":"No need, don't bother, it's unnecessary. A casual dismissal of something not required."},
    {"word":"own goal","type":"phrase","pronunciation":"own goal","meaning":"To sabotage yourself or cause your own downfall. Scoring against yourself \u2014 football metaphor."},
    {"word":"stunned like vegetable","type":"phrase","pronunciation":"stunned like veg-e-ta-ble","meaning":"Completely frozen, shocked into immobility. A uniquely Singaporean way to describe total stupefaction."},
    {"word":"free free","type":"phrase","pronunciation":"free free","meaning":"For free, without any cost, gratis. The repetition emphasises that something costs nothing."},
    {"word":"good lah","type":"phrase","pronunciation":"good lah","meaning":"That's good, well done, or that works. A simple, warm expression of approval or relief."},
    {"word":"steady lah","type":"phrase","pronunciation":"steady lah","meaning":"That's impressive or great. Affirming that someone or something is doing well."},
    {"word":"steady sia","type":"phrase","pronunciation":"steady see-ah","meaning":"Wow, that's really impressive or reliable. 'Steady' amplified with the 'sia' emphasis particle."},
    {"word":"steady or not","type":"phrase","pronunciation":"steady or not","meaning":"Are you reliable for this? Can you handle it? A check on someone's readiness and commitment."},
    {"word":"come lah","type":"phrase","pronunciation":"come lah","meaning":"Come on, let's go, come along. An invitation or encouragement to join or get moving."},
    {"word":"don't liddat lah","type":"phrase","pronunciation":"don't lih-dat lah","meaning":"Don't be like that, don't act that way. A gentle rebuke when someone is being unreasonable."},
    {"word":"buay steady","type":"phrase","pronunciation":"boo-ay steady","meaning":"Unable to cope, unstable, not keeping it together. The opposite of steady."},
    {"word":"jio me","type":"phrase","pronunciation":"jee-oh me","meaning":"Invite me along! Include me! An enthusiastic request to be brought into a plan."},
    {"word":"jio or not","type":"phrase","pronunciation":"jee-oh or not","meaning":"Are you going to invite me or not? A direct nudge when you want to be included."},
    {"word":"mai tu liao","type":"phrase","pronunciation":"my-too-lee-ow","meaning":"Don't delay anymore, stop dilly-dallying. 'Just get on with it already.'"},
    {"word":"eat already","type":"phrase","pronunciation":"eat already","meaning":"Have you eaten yet? The classic Singaporean greeting that substitutes for 'how are you?'"},
    {"word":"blur blur","type":"phrase","pronunciation":"blur blur","meaning":"In a daze, vaguely confused, or going through motions without full awareness."},
    {"word":"not bad lah","type":"phrase","pronunciation":"not bad lah","meaning":"That's actually quite good. Singapore understatement \u2014 'not bad' often means quite impressive."},
    {"word":"last bus","type":"phrase","pronunciation":"last bus","meaning":"The last chance, the final opportunity. Missing the last bus means missing out entirely."},
    {"word":"long snake","type":"phrase","pronunciation":"long snake","meaning":"A very long queue. The visual metaphor of a queue winding like a snake."},
    {"word":"uncle-uncle","type":"adjective","pronunciation":"uncle-uncle","meaning":"Old-fashioned, not trendy, or stuck in outdated ways. Describes something behind the times."},
    {"word":"no lah","type":"phrase","pronunciation":"no lah","meaning":"Of course not, definitely not. A soft but clear denial with the 'lah' particle softening the rejection."},
    {"word":"got lah","type":"phrase","pronunciation":"got lah","meaning":"Of course there is, it definitely exists. Assertive confirmation that something is present or real."},
    {"word":"sleep liao","type":"phrase","pronunciation":"sleep lee-ow","meaning":"Already gone to sleep, zonked out. Used when someone has passed out or you're about to."},
    {"word":"done liao","type":"phrase","pronunciation":"done lee-ow","meaning":"Already done, finished, completed. A clean and final statement of task completion."},
    {"word":"off liao","type":"phrase","pronunciation":"off lee-ow","meaning":"Switched off, done for the day, finished up. Something is powered down or completed."},
    {"word":"dunno leh","type":"phrase","pronunciation":"dun-no leh","meaning":"I don't really know, I'm not sure. A soft, slightly uncertain 'I don't know' with the 'leh' softener."},
    {"word":"like that also can","type":"phrase","pronunciation":"like that also can","meaning":"That method also works? Expressing mild surprise that something unorthodox is acceptable."},
    {"word":"got issue","type":"phrase","pronunciation":"got issue","meaning":"There's a problem, something is wrong. A casual way to flag that something needs attention."},
    {"word":"cannot tahan","type":"phrase","pronunciation":"cannot tah-han","meaning":"Cannot endure or stand it. English-Malay hybrid version of 'buay tahan'."},
    {"word":"best one","type":"phrase","pronunciation":"best one","meaning":"The best! Used as emphatic praise with the Singlish particle 'one' for assertion."},
    {"word":"cannot be","type":"phrase","pronunciation":"cannot be","meaning":"That can't be right, that's impossible. Strong disbelief at an unlikely situation."},
    {"word":"extra","type":"adjective","pronunciation":"extra","meaning":"Over the top, trying too hard, doing more than is needed or appropriate."},
    {"word":"face palm","type":"verb / exclamation","pronunciation":"face palm","meaning":"A moment of embarrassed or exasperated disbelief \u2014 covering your face with your hand."},
    {"word":"free and easy","type":"phrase","pronunciation":"free and easy","meaning":"Unscheduled, self-directed time. A free itinerary day with no fixed agenda to follow."},
    {"word":"own time own target","type":"phrase","pronunciation":"own time own target","meaning":"At your own pace, when you're ready, no rush. NS-origin phrase meaning proceed when individually ready."},
    {"word":"kena sabo","type":"phrase","pronunciation":"keh-nah sah-bo","meaning":"Got sabotaged, was set up. Combining 'kena' (to get) and 'sabo' into one expression."},
    {"word":"chop stamp","type":"phrase","pronunciation":"chop stamp","meaning":"To officially confirm or seal something. Derived from rubber stamps used on official documents."},
    {"word":"no choice lor","type":"phrase","pronunciation":"no choice lor","meaning":"There's nothing else to be done about it. More resigned version of 'no choice' with the 'lor' particle."},
    {"word":"shiok ah","type":"phrase","pronunciation":"shee-ok ah","meaning":"That's great! Used as a satisfied response or to confirm something is enjoyable."},
    {"word":"eye power","type":"phrase","pronunciation":"eye power","meaning":"Watching and doing nothing to help while others work. Ironically called 'using eye power'."},
    {"word":"jialat sia","type":"phrase","pronunciation":"jee-ah-lat see-ah","meaning":"That's really bad, dire, or serious. The 'sia' particle adds extra emphasis to jialat."},
    {"word":"siao liao","type":"phrase","pronunciation":"see-ow lee-ow","meaning":"We're in trouble, this has gone crazy. 'Siao' intensified with 'liao' indicating it's already happened."},
    {"word":"power up","type":"phrase","pronunciation":"power up","meaning":"To energise, prepare intensely, or ramp up before a big moment. Charging up before going all out."},
    {"word":"show hand","type":"phrase","pronunciation":"show hand","meaning":"To go all in, reveal everything, or commit completely. From card games \u2014 showing all your cards."},
    {"word":"cut queue","type":"phrase","pronunciation":"cut queue","meaning":"To skip the line or push in front of others. A major social offence in Singapore queue culture."},
    {"word":"see through","type":"phrase","pronunciation":"see through","meaning":"To see past someone's act or intention \u2014 to not be fooled by a pretence."},
    {"word":"make noise","type":"phrase","pronunciation":"make noise","meaning":"To complain loudly, protest, or create a fuss about something. Stirring up trouble by being vocal."},
    {"word":"open eyes","type":"phrase","pronunciation":"open eyes","meaning":"An eye-opening experience \u2014 seeing something new and impressive for the first time."},
    {"word":"orbi","type":"exclamation","pronunciation":"or-bee","meaning":"Short form of 'orbi good'. Serves you right \u2014 used when someone gets what they deserve."},
    {"word":"jaga","type":"verb","pronunciation":"jah-gah","meaning":"To look after, guard, or take care of. From Malay \u2014 used for watching over people or things."},
    {"word":"hao lian max","type":"phrase","pronunciation":"hao lee-en max","meaning":"At the peak of showing off. An intensified 'hao lian' for someone being incredibly boastful."},
    {"word":"action king","type":"phrase","pronunciation":"action king","meaning":"Someone who shows off constantly. The 'king' title added for someone whose 'action' is legendary."},
    {"word":"siam lah","type":"phrase","pronunciation":"see-am lah","meaning":"Get out of the way! A more emphatic 'siam' with 'lah' for urgency."},
    {"word":"wait ah","type":"phrase","pronunciation":"wait ah","meaning":"Wait a moment, hold on. A casual way to ask someone to pause while you do something."},
    {"word":"faster lah","type":"phrase","pronunciation":"faster lah","meaning":"Hurry up lah. A direct, slightly impatient call to speed things up."},
    {"word":"die lah","type":"phrase","pronunciation":"die lah","meaning":"We're finished, that's it for us. A dramatic expression of being in serious trouble."},
    {"word":"how liddat","type":"phrase","pronunciation":"how lih-dat","meaning":"How did it end up like this? Expressing disbelief or exasperation at a strange outcome."},
    {"word":"for what","type":"phrase","pronunciation":"for what","meaning":"Why? What's the purpose of that? A Singlish alternative to 'why' or 'what for'."},
    {"word":"what for","type":"phrase","pronunciation":"what for","meaning":"Why bother? What is the point? Rhetorical question dismissing something unnecessary."},
    {"word":"how come","type":"phrase","pronunciation":"how come","meaning":"Why? How did this happen? Used to ask for an explanation or express surprise."},
    {"word":"say already","type":"phrase","pronunciation":"say already","meaning":"I already told you, I already said it. Used when repeating something that was previously stated."},
    {"word":"never say","type":"phrase","pronunciation":"never say","meaning":"Didn't say that. A past-tense denial \u2014 'I never said that.'"},
    {"word":"true or not","type":"phrase","pronunciation":"true or not","meaning":"Is that true? Really? Asking for confirmation that something is accurate."},
    {"word":"real one","type":"phrase","pronunciation":"real one","meaning":"It's genuine, it's for real. Confirming that something is authentic or serious."},
    {"word":"want or not","type":"phrase","pronunciation":"want or not","meaning":"Do you want it or not? A direct, slightly impatient question about someone's preference."},
    {"word":"ready or not","type":"phrase","pronunciation":"ready or not","meaning":"Are you ready? Used to check if someone is prepared, often with mild urgency."},
    {"word":"now or later","type":"phrase","pronunciation":"now or later","meaning":"When do you want to do this \u2014 now or at a later time? A simple scheduling question."},
    {"word":"here or not","type":"phrase","pronunciation":"here or not","meaning":"Are you here/present? Are you paying attention? Checking if someone is physically or mentally present."},
    {"word":"sure or not","type":"phrase","pronunciation":"sure or not","meaning":"Are you sure? Is that certain? Seeking confirmation that someone is confident in their claim."},
    {"word":"go or not","type":"phrase","pronunciation":"go or not","meaning":"Are we going or not? A direct question about whether a plan is happening."},
    {"word":"eat or not","type":"phrase","pronunciation":"eat or not","meaning":"Are you eating or not? Checking if someone is going to join a meal."},
    {"word":"know already","type":"phrase","pronunciation":"know already","meaning":"I already know. Used to indicate awareness of something, often slightly impatiently."},
    {"word":"later lah","type":"phrase","pronunciation":"later lah","meaning":"Later, I'll do it later. A relaxed deferral \u2014 not necessarily meaning it will happen soon."},
    {"word":"tomorrow lah","type":"phrase","pronunciation":"tomorrow lah","meaning":"Tomorrow can do. A casual postponement, sometimes used as a gentle brush-off."},
    {"word":"next time lah","type":"phrase","pronunciation":"next time lah","meaning":"Next time lah. Indefinite deferral \u2014 could mean next occasion, could mean never."},
    {"word":"up to you lah","type":"phrase","pronunciation":"up to you lah","meaning":"It's your decision, I don't mind. Giving the other person full choice."},
    {"word":"whatever lah","type":"phrase","pronunciation":"whatever lah","meaning":"Whatever, I don't care. Resigned indifference, often with mild frustration."},
    {"word":"like that lor","type":"phrase","pronunciation":"like that lor","meaning":"That's just how it is. Resigned acceptance of a situation \u2014 nothing to be done."},
    {"word":"then like that lor","type":"phrase","pronunciation":"then like that lor","meaning":"Then that's how it'll be. A resigned conclusion following a 'then how' type question."},
    {"word":"cannot one","type":"phrase","pronunciation":"cannot one","meaning":"It just can't be done, it's not possible. Assertive statement that something cannot happen."},
    {"word":"very can","type":"phrase","pronunciation":"very can","meaning":"Very capable of it, very much possible. An emphatic confirmation that something is doable."},
    {"word":"steady already","type":"phrase","pronunciation":"steady already","meaning":"Already stable and ready. Confirming that everything is in order and prepared."},
    {"word":"done deal","type":"phrase","pronunciation":"done deal","meaning":"It's settled, no more discussion needed. A final confirmation that something is agreed."},
    {"word":"win liao lor","type":"phrase","pronunciation":"win lee-ow lor","meaning":"We've lost, I give up, you win. Sardonic resignation \u2014 admitting defeat with dry humour."},
    {"word":"die already","type":"phrase","pronunciation":"die already","meaning":"It's finished, we're done for. Dramatic declaration that something has been ruined."},
    {"word":"mati liao","type":"phrase","pronunciation":"mah-tee lee-ow","meaning":"Dead already, we're in serious trouble. Malay 'mati' combined with 'liao' for finality."},
    {"word":"habis liao","type":"phrase","pronunciation":"hah-bis lee-ow","meaning":"All finished, totally done for. Malay 'habis' with 'liao' \u2014 completely used up or ruined."},
    {"word":"wa lao","type":"exclamation","pronunciation":"wah-lau","meaning":"Variant of 'walao' \u2014 expressing exasperation, disbelief, or mild frustration."},
    {"word":"eh sai","type":"phrase","pronunciation":"ay-sigh","meaning":"Can, acceptable, that's okay. Hokkien way of saying something is permissible or possible."},
    {"word":"mm sai","type":"phrase","pronunciation":"mm-sigh","meaning":"No need, don't need to. Cantonese way of saying something is unnecessary."},
    {"word":"ho say bo","type":"phrase","pronunciation":"hoh-say-boh","meaning":"Is everything okay? Are things going well? Hokkien check-in phrase."},
    {"word":"zao bo","type":"phrase","pronunciation":"zow-boh","meaning":"Already ran away? Already left? Used to ask if someone has fled a situation."},
    {"word":"buy already","type":"phrase","pronunciation":"buy already","meaning":"Already bought. Past-tense Singlish construction using 'already' as a completive marker."},
    {"word":"call already","type":"phrase","pronunciation":"call already","meaning":"Already called. Used to confirm a call has been made, often to pre-empt being asked."},
    {"word":"send already","type":"phrase","pronunciation":"send already","meaning":"Already sent. Confirming a message, file, or person has been dispatched."},
    {"word":"tell already","type":"phrase","pronunciation":"tell already","meaning":"Already told. Used when confirming information was passed on, often with mild exasperation."},
    {"word":"see already","type":"phrase","pronunciation":"see already","meaning":"Already seen it. Confirming that something has been viewed or noticed."},
    {"word":"come already","type":"phrase","pronunciation":"come already","meaning":"Already arrived. Used to announce or confirm arrival at a destination."},
    {"word":"go already","type":"phrase","pronunciation":"go already","meaning":"Already left. Confirming someone or something has departed."},
    {"word":"finish already","type":"phrase","pronunciation":"finish already","meaning":"Already finished. Confirming that a task or quantity is completely done or used up."},
    {"word":"on the way","type":"phrase","pronunciation":"on the way","meaning":"Coming, in transit. Used to reassure someone you're heading to them \u2014 Singapore's '5 minutes'."},
    {"word":"reaching","type":"phrase","pronunciation":"reaching","meaning":"About to arrive. The Singaporean text message that means you're close but still some minutes away."},
    {"word":"five minutes","type":"phrase","pronunciation":"five minutes","meaning":"Almost there \u2014 the famous Singapore '5 minutes' which can mean anywhere from 1 to 30 minutes."},
    {"word":"orh kay","type":"phrase","pronunciation":"or-kay","meaning":"Okay, alright, understood. A Singlish rendering of \"okay\" with a local flavour \u2014 casual acknowledgement."},
    {"word":"ORD loh","type":"exclamation / phrase","pronunciation":"O-R-D loh","meaning":"Operationally Ready Date \u2014 the day an NSF finishes full-time NS and is officially discharged. Shouted with maximum relief and celebration."},
    {"word":"bookout","type":"verb / noun","pronunciation":"book-out","meaning":"To leave camp on weekends or approved leave. The most anticipated event in any NSF's week."},
    {"word":"bookin","type":"verb / noun","pronunciation":"book-in","meaning":"To return to camp after bookout. The most dreaded event in any NSF's week."},
    {"word":"occifer","type":"noun","pronunciation":"ok-si-fer","meaning":"NSF slang for 'officer' \u2014 used with gentle mockery. The exaggerated pronunciation reflects the rank-and-file relationship with officers."},
    {"word":"wadio","type":"noun","pronunciation":"wah-dee-oh","meaning":"Army slang for 'radio'. The distinctive pronunciation comes from how signals are called out on the field. Widely used humorously outside NS too."},
    {"word":"saikang","type":"noun / verb","pronunciation":"sai-kang","meaning":"Literally 'shit work' in Hokkien. Menial, unglamorous tasks that nobody wants but someone always kena. Used widely in civilian life too."},
    {"word":"saikang warrior","type":"noun","pronunciation":"sai-kang warrior","meaning":"Someone who always ends up doing the saikang. Either very suay, very kiasu about helping, or just the easiest person to arrow."},
    {"word":"goreng","type":"verb","pronunciation":"goh-reng","meaning":"To scold, punish, or tear someone apart verbally. From Malay 'fry' \u2014 when your sergeant goreng you, you feel like you've been fried alive."},
    {"word":"chao recruit","type":"noun","pronunciation":"chow re-croot","meaning":"A brand-new, inexperienced recruit \u2014 still smelling of civilian life. Used affectionately or condescendingly. Now applied to any newbie in any context."},
    {"word":"chiong sua","type":"phrase","pronunciation":"chee-ong sua","meaning":"Literally 'charge the hill' in Hokkien. To go all out, rush forward, or tackle something with maximum aggression and commitment."},
    {"word":"siong","type":"adjective","pronunciation":"see-ong","meaning":"Tough, suffering, or physically gruelling. Describes brutal training, terrible situations, or anything that makes your body and soul ache."},
    {"word":"outfield","type":"noun / adjective","pronunciation":"out-field","meaning":"Going into the field for military exercises \u2014 sleeping in jungle, eating rations, zero comfort. Also used to mean any situation far from civilisation."},
    {"word":"confinement","type":"noun","pronunciation":"con-fine-ment","meaning":"Being confined to camp as punishment \u2014 no bookout, no freedom. Used humorously in civilian life to mean being stuck somewhere against your will."},
    {"word":"tekong","type":"noun","pronunciation":"teh-kong","meaning":"Pulau Tekong \u2014 the island where all SAF BMT takes place. Saying you're 'going Tekong' means you're about to start NS. A place of legend and suffering."},
    {"word":"BMT","type":"noun","pronunciation":"B-M-T","meaning":"Basic Military Training \u2014 the first phase of NS where civilians are turned into soldiers. Nine weeks of tekong life that everyone has a war story about."},
    {"word":"keng","type":"verb / adjective","pronunciation":"keng","meaning":"To malinger, fake illness, or avoid duties. The art of appearing unfit while being perfectly fine. A revered skill in NS culture."},
    {"word":"keng king","type":"noun","pronunciation":"keng king","meaning":"The undisputed master of kenging \u2014 always sick, always downgraded, always somehow unavailable for the siong stuff. Respected and resented in equal measure."},
    {"word":"fall in","type":"command / phrase","pronunciation":"fall in","meaning":"The command to assemble and form up immediately. Shouted by commanders, now used by anyone trying to gather a group. 'Eh, fall in already!'"},
    {"word":"fall out","type":"command / phrase","pronunciation":"fall out","meaning":"The command to dismiss and disperse. The best two words in any NS formation. Also used casually to mean 'let's break' or 'we're done here'."},
    {"word":"stand by bed","type":"phrase","pronunciation":"stand by bed","meaning":"Bunk inspection mode \u2014 everything folded, aligned, squared off to the millimetre. Extreme standards. Used outside NS to mean being completely ready and prepped."},
    {"word":"IPPT","type":"noun","pronunciation":"I-P-P-T","meaning":"Individual Physical Proficiency Test \u2014 the annual fitness test every NSman must pass. Gold, Silver, or Pass. Failing means RT. Source of much anxiety for reservists."},
    {"word":"RT","type":"noun","pronunciation":"R-T","meaning":"Remedial Training \u2014 extra physical sessions for those who fail IPPT. The punishment fitness programme. Everyone knows someone who's perpetually in RT."},
    {"word":"reservist","type":"noun","pronunciation":"re-zer-vist","meaning":"An NSman doing ICT \u2014 the annual in-camp training after full-time NS ends. The yearly disruption to civilian life that every Singaporean son dreads."},
    {"word":"ICT","type":"noun","pronunciation":"I-C-T","meaning":"In-Camp Training \u2014 the reservist cycles after ORD. You go back to camp, put on your old uniform, and try to fit it. Usually held at the worst possible time."},
    {"word":"cookhouse","type":"noun","pronunciation":"cook-house","meaning":"The army canteen where all meals are served. Cookhouse food is legendary for being either surprisingly decent or completely unidentifiable."},
    {"word":"blur cock","type":"adjective / noun","pronunciation":"blur cock","meaning":"Extremely blur, hopelessly clueless. An intensified version of 'blur' from NS vocabulary. Now used broadly for anyone who is spectacularly unaware of what's going on."},
    {"word":"wayang king","type":"noun","pronunciation":"wah-yang king","meaning":"The ultimate wayang practitioner \u2014 someone who puts on the biggest show of working hard while doing absolutely nothing. A title earned through dedication to the craft."},
    {"word":"rabak","type":"adjective","pronunciation":"rah-bak","meaning":"Chaotic, messy, out of control. From Malay \u2014 widely used in NS to describe situations that have gone completely off the rails. Now common in civilian slang too."},
    {"word":"extra duty","type":"noun","pronunciation":"extra duty","meaning":"NS punishment \u2014 assigned additional guard duty or camp tasks for misconduct. Being 'given extra' is something you tell your children as a cautionary tale."},
    {"word":"arrow king","type":"noun","pronunciation":"arrow king","meaning":"The person who gets arrowed for everything. Somehow always the one chosen for saikang, extra duties, and all the jobs nobody wants. Usually the most obliging person."},
    {"word":"chao keng","type":"phrase","pronunciation":"chow keng","meaning":"To fake illness or injury to avoid duties \u2014 the NS-specific version of 'zao geng'. A time-honoured tradition. Medical centre visits spike dramatically before outfield."},
    {"word":"PES C","type":"noun","pronunciation":"P-E-S C","meaning":"A downgraded physical employment status in NS \u2014 meaning you're not fit for combat roles. Getting PES C is both a relief and a source of teasing from your platoon."},
    {"word":"tekong face","type":"phrase","pronunciation":"teh-kong face","meaning":"The tired, weathered, suntanned look of someone who just came back from BMT or outfield. A specific kind of exhaustion that only Tekong can produce."},
    {"word":"smoke break","type":"noun","pronunciation":"smoke break","meaning":"The unofficial rest break in NS life \u2014 whether you smoke or not, it's a social gathering. Now used for any short break from work or duties."},
    {"word":"wgt wadio","type":"phrase","pronunciation":"W-G-T wah-dee-oh","meaning":"Where Got Time \u2014 shouted over the (w)radio. Classic NS complaint that you have zero bandwidth for whatever is being asked of you. The definitive NSF response to any unreasonable request."},
    {"word":"knnccb","type":"exclamation","pronunciation":"K-N-N-C-C-B","meaning":"Kan ni na chao chee bye \u2014 the nuclear option of Hokkien vulgarities. A compound expletive combining maternal and anatomical insults. Reserved for peak outrage. Saying the full acronym alone in any kopitiam communicates the complete emotional situation.","nsfw":True},
    {"word":"ccb","type":"exclamation","pronunciation":"C-C-B","meaning":"Chao chee bye \u2014 a major Hokkien expletive. Used as an exclamation of frustration, disbelief, or extreme irritation. The 'chao' intensifies the base term considerably.","nsfw":True},
    {"word":"cb","type":"exclamation","pronunciation":"C-B","meaning":"Chee bye \u2014 a Hokkien vulgarity used as a general strong expletive. Milder than ccb in casual usage. Extremely versatile \u2014 can express shock, admiration, frustration, or anything in between depending on tone.","nsfw":True},
    {"word":"knn","type":"exclamation","pronunciation":"K-N-N","meaning":"Kan ni na \u2014 a Hokkien maternal expletive. One step below knnccb on the escalation ladder. The go-to when something is seriously frustrating but not quite full nuclear.","nsfw":True},
    {"word":"kns","type":"exclamation","pronunciation":"K-N-S","meaning":"Kan ni sai \u2014 literally 'your mother's shit'. A milder Hokkien expletive compared to knn. Used more casually and with less weight \u2014 the everyday frustration release valve.","nsfw":True},
    {"word":"kaninah","type":"exclamation","pronunciation":"kah-nee-nah","meaning":"Hokkien maternal expletive \u2014 the full spoken-out version of knn. Used when you want to express the sentiment more dramatically rather than just firing off the acronym.","nsfw":True},
    {"word":"lan jiao","type":"noun / exclamation","pronunciation":"lan-jee-ow","meaning":"Hokkien anatomical expletive (male). Used as a dismissive 'what the hell', an expression of disbelief, or attached to another word for intensification. 'Lan jiao lah' is a complete sentence.","nsfw":True},
    {"word":"cheebye","type":"exclamation / adjective","pronunciation":"chee-bye","meaning":"Full written-out form of cb. Used in text when you want the full effect rather than the acronym. Can precede a noun to describe something terrible: 'cheebye weather', 'cheebye traffic'.","nsfw":True},
    {"word":"pukimak","type":"exclamation","pronunciation":"poo-kee-mak","meaning":"Malay equivalent of the Hokkien maternal vulgarities. Used across communities \u2014 particularly expressive when deployed with rising intonation. The Malay community's contribution to the Singapore expletive canon.","nsfw":True},
    {"word":"simi cb","type":"phrase","pronunciation":"see-mee C-B","meaning":"What the hell is this? A crude version of 'simi sai' \u2014 combining Hokkien 'what' with the expletive for extra exasperation. What you say when simi sai isn't strong enough.","nsfw":True},
    {"word":"lanciao","type":"noun / exclamation","pronunciation":"lan-chee-ow","meaning":"Alternate compound spelling of lan jiao. Used identically \u2014 as dismissal, disbelief, or intensifier. 'You lanciao talking about what?' is a perfectly formed Singlish question.","nsfw":True},
    {"word":"cb face","type":"phrase","pronunciation":"C-B face","meaning":"Describing someone's expression as sour, unpleasant, or irritating. The rude Singlish way to say someone looks permanently annoyed or unfriendly. Not recommended as a compliment.","nsfw":True},
]
